spring:
  datasource:
    url: jdbc:postgresql:stex
    username: stex
    password: stex
    driver-class-name: org.postgresql.Driver

  messages:
    basename: i18n/messages

  transaction:
    rollback-on-commit-failure: true

dozer:
  mapping-files: classpath:dozer/java8-mappings.xml

mybatis:
  config-location: classpath:mybatis-config.xml
